apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-c1pk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-c1pk
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-c1pk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-c1pk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-c1pk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-khzf-tenant/rhtap-demo-app/hacbs-test-project-c1pk@sha256:d5cd2007846b35ac55ddd17945fa3684802081a4e33aa6c086930319d728bec5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
